---
- hosts: RaspberryPi
  vars_files:
   - vars.yml

  tasks:

   - name: Check if modprobe file exists
     stat:
      path: /etc/modprobe.d/cfg80211.conf
     register: stat_result

   - name: Set modprob file file
     become: yes
     shell: echo "options cfg80211 ieee80211_regdom={{ region }}"  >  /etc/modprobe.d/cfg80211.conf
     when: stat_result.stat.exists == False

   - name: Install Regulatory DB for wifi settings
     apt:
       name: wireless-regdb
       state: present

   - name: Install iw
     apt:
       name: iw
       state: present

   - name: Install CRDA  (Central Regulatory Domain Agent)
     apt:
       name: crda
       state: present

   - name: Get region/country status on device
     command: /sbin/iw reg get
     register: result

   - name: Set region/country if not done
     become: yes
     command: /sbin/iw reg set {{ region }}
     when: '"country 00" in result.stdout'

   - name: Create destination directory
     file: 
       path: /home/osmc/addons/ 
       state: directory
       owner: osmc
       group: osmc
       mode: 0775

   - name: Copy Youtube addon To Kodi
     copy:
       src: AddOns/plugin.video.youtube-5.5.1.zip
       dest: /home/osmc/addons/plugin.video.youtube-5.5.1.zip
       owner: osmc
       group: osmc
       mode: 0775
       
   - name: Copy DailyMotion addon To Kodi
     copy:
       src: AddOns/plugin.video.dailymotion-0.2.5.zip
       dest: /home/osmc/addons/plugin.video.dailymotion-0.2.5.zip
       owner: osmc
       group: osmc
       mode: 0775

   - name: Copy Kodil repository To Kodi
     copy:
       src: AddOns/repository.kodil-1.0.1.zip
       dest: /home/osmc/addons/repository.kodil-1.0.1.zip
       owner: osmc
       group: osmc
       mode: 0775
